### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by henne49** [JensVanhooydonck/xknx-configuration-importer#2]
Hi Jens, great idea, I thought it would be great to have an importer. 

I'm more than happy to test and help, where I can. 
cheers

**Comment by JensVanhooydonck** [comment]
Hi,

I've updated the project to generate a basic xknx.yaml file. 
I still need to write the readme. But you can try it out if you like.

You do need to use the ETS Functions [https://support.knx.org/hc/en-us/articles/115003448449-Functions](url)


Jens

**Comment by henne49** [comment]
good news, but then I have to rework my installation. Good that I did only some testing so far and not the final house. So will need some more time, then I will rebuild from scratch with functions in mind.
